---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```

# GAA

This is the GitHub Repository for the Gambling Addicts Annonymous fantasy football team.

## Current teams
* AGUS [Commisioner]
* BILL
* CART
* KIER [League Manager]
* KYLE
* NICK *(Champ)*
* PEPE
* CORY
* ~~COLN~~
* ~~GRIZ~~
* ~~CHAR~~
* ~~ROWN~~ *(Griz)*

## Standings

```{r libs, warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(fflr)
```

```{r download_record, echo=FALSE, message=FALSE, warning=FALSE}
record <- tibble()
for (i in 2015:2018) {
  data <- ffl_get(252353, view = "roster", seasonId = i, current = FALSE)[[1]]
  transpose(transpose(data$teams)$record)$overall %>% 
    map_df(as_tibble) %>% 
    mutate(
      year = as.character(data$seasonId),
      id = as_vector(transpose(data$teams)$primaryOwner),
      rank = as_vector(transpose(data$teams)$rankCalculatedFinal)
    ) %>% 
    group_by(id) %>% 
    arrange(desc(wins)) %>% 
    slice(1) %>% 
    ungroup() %>% 
    left_join(select(map_dfr(data$members, as_tibble), id, firstName)) %>% 
    select(
      year,
      firstName,
      rank,
      wins, 
      losses, 
      pointsFor, 
      pointsAgainst
    ) %>% 
    arrange(rank) %>% 
    bind_rows(record) -> record
}
```

### 2018

```{r standings_2018, echo=FALSE}
record %>% 
  filter(year == 2018) %>% 
  select(-year) %>% 
  arrange(rank) %>% 
  kable(
    digits = 2, 
    col.names = c("Team", 
                  "Rank", 
                  "Wins", 
                  "Losses", 
                  "Points For",
                  "Points Against")
  )
```

### 2017

```{r standings_2017, echo=FALSE}
record %>% 
  filter(year == 2017) %>% 
  select(-year) %>%  
  arrange(rank) %>% 
  kable(
    digits = 2, 
    col.names = c("Team", 
                  "Rank", 
                  "Wins", 
                  "Losses", 
                  "Points For",
                  "Points Against")
  )
```

### 2016

```{r standings_2016, echo=FALSE}
record %>% 
  filter(year == 2016) %>% 
  select(-year) %>%  
  arrange(rank) %>% 
  kable(
    digits = 2, 
    col.names = c("Team", 
                  "Rank", 
                  "Wins", 
                  "Losses", 
                  "Points For",
                  "Points Against")
  )
```

### 2015

```{r standings_2015, echo=FALSE}
record %>% 
  filter(year == 2015) %>% 
  select(-year) %>% 
  arrange(rank) %>% 
  kable(
    digits = 2, 
    col.names = c("Team", 
                  "Rank", 
                  "Wins", 
                  "Losses", 
                  "Points For",
                  "Points Against")
  )
```

